// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fmp.proto

package fmp_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//A structure containing all the devices listed in the network repo.
type Devices struct {
	Devices   map[string]*Device `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Timestamp int64              `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	//Extra information describing locality positions
	Localities           map[string]*Locality `protobuf:"bytes,3,rep,name=localities,proto3" json:"localities,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Devices) Reset()         { *m = Devices{} }
func (m *Devices) String() string { return proto.CompactTextString(m) }
func (*Devices) ProtoMessage()    {}
func (*Devices) Descriptor() ([]byte, []int) {
	return fileDescriptor_936908a87da5a9ce, []int{0}
}

func (m *Devices) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devices.Unmarshal(m, b)
}
func (m *Devices) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devices.Marshal(b, m, deterministic)
}
func (m *Devices) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devices.Merge(m, src)
}
func (m *Devices) XXX_Size() int {
	return xxx_messageInfo_Devices.Size(m)
}
func (m *Devices) XXX_DiscardUnknown() {
	xxx_messageInfo_Devices.DiscardUnknown(m)
}

var xxx_messageInfo_Devices proto.InternalMessageInfo

func (m *Devices) GetDevices() map[string]*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

func (m *Devices) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Devices) GetLocalities() map[string]*Locality {
	if m != nil {
		return m.Localities
	}
	return nil
}

type Device struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ipaddr               string   `protobuf:"bytes,2,opt,name=ipaddr,proto3" json:"ipaddr,omitempty"`
	Model                string   `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Sitecode             string   `protobuf:"bytes,4,opt,name=sitecode,proto3" json:"sitecode,omitempty"`
	Locality             string   `protobuf:"bytes,5,opt,name=locality,proto3" json:"locality,omitempty"`
	Tags                 []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_936908a87da5a9ce, []int{1}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Device) GetIpaddr() string {
	if m != nil {
		return m.Ipaddr
	}
	return ""
}

func (m *Device) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Device) GetSitecode() string {
	if m != nil {
		return m.Sitecode
	}
	return ""
}

func (m *Device) GetLocality() string {
	if m != nil {
		return m.Locality
	}
	return ""
}

func (m *Device) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Locality struct {
	Locality             string   `protobuf:"bytes,1,opt,name=locality,proto3" json:"locality,omitempty"`
	Latitude             float32  `protobuf:"fixed32,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Locality) Reset()         { *m = Locality{} }
func (m *Locality) String() string { return proto.CompactTextString(m) }
func (*Locality) ProtoMessage()    {}
func (*Locality) Descriptor() ([]byte, []int) {
	return fileDescriptor_936908a87da5a9ce, []int{2}
}

func (m *Locality) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Locality.Unmarshal(m, b)
}
func (m *Locality) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Locality.Marshal(b, m, deterministic)
}
func (m *Locality) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Locality.Merge(m, src)
}
func (m *Locality) XXX_Size() int {
	return xxx_messageInfo_Locality.Size(m)
}
func (m *Locality) XXX_DiscardUnknown() {
	xxx_messageInfo_Locality.DiscardUnknown(m)
}

var xxx_messageInfo_Locality proto.InternalMessageInfo

func (m *Locality) GetLocality() string {
	if m != nil {
		return m.Locality
	}
	return ""
}

func (m *Locality) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Locality) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func init() {
	proto.RegisterType((*Devices)(nil), "fmp.Devices")
	proto.RegisterMapType((map[string]*Device)(nil), "fmp.Devices.DevicesEntry")
	proto.RegisterMapType((map[string]*Locality)(nil), "fmp.Devices.LocalitiesEntry")
	proto.RegisterType((*Device)(nil), "fmp.Device")
	proto.RegisterType((*Locality)(nil), "fmp.Locality")
}

func init() { proto.RegisterFile("fmp.proto", fileDescriptor_936908a87da5a9ce) }

var fileDescriptor_936908a87da5a9ce = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xb1, 0x6e, 0xf2, 0x30,
	0x14, 0x85, 0xe5, 0x18, 0x02, 0xb9, 0xfc, 0xbf, 0x5a, 0x59, 0x55, 0xe5, 0x22, 0x86, 0x94, 0x2e,
	0x99, 0x18, 0x60, 0xa9, 0xaa, 0x4e, 0x55, 0xab, 0x2e, 0x4c, 0x1e, 0xbb, 0xb4, 0x86, 0x18, 0x6a,
	0x35, 0xc6, 0x16, 0x31, 0x48, 0x79, 0x99, 0xbe, 0x43, 0xdf, 0xb0, 0xb2, 0x9d, 0x40, 0x40, 0x9d,
	0x72, 0xcf, 0x3d, 0xf7, 0x7e, 0x27, 0x89, 0x0d, 0xc9, 0x4a, 0x99, 0x89, 0xd9, 0x6a, 0xab, 0x09,
	0x5e, 0x29, 0x33, 0xfe, 0x89, 0xa0, 0xf7, 0x2c, 0xf6, 0x72, 0x29, 0x4a, 0x32, 0x83, 0x5e, 0x1e,
	0x4a, 0x8a, 0x52, 0x9c, 0x0d, 0xa6, 0x37, 0x13, 0x37, 0x5d, 0xdb, 0xcd, 0xf3, 0x65, 0x63, 0xb7,
	0x15, 0x6b, 0x26, 0xc9, 0x08, 0x12, 0x2b, 0x95, 0x28, 0x2d, 0x57, 0x86, 0x46, 0x29, 0xca, 0x30,
	0x3b, 0x36, 0xc8, 0x23, 0x40, 0xa1, 0x97, 0xbc, 0x90, 0x56, 0x8a, 0x92, 0x62, 0x4f, 0x1d, 0x9d,
	0x50, 0xe7, 0x07, 0x3b, 0x80, 0x5b, 0xf3, 0xc3, 0x57, 0xf8, 0xd7, 0x0e, 0x25, 0x97, 0x80, 0xbf,
	0x44, 0x45, 0x51, 0x8a, 0xb2, 0x84, 0xb9, 0x92, 0xdc, 0x42, 0x77, 0xcf, 0x8b, 0x9d, 0xf0, 0xc9,
	0x83, 0xe9, 0xa0, 0x85, 0x66, 0xc1, 0x79, 0x88, 0xee, 0xd1, 0x70, 0x0e, 0x17, 0x67, 0x39, 0x7f,
	0xb0, 0xee, 0x4e, 0x59, 0xff, 0x3d, 0xab, 0x5e, 0xab, 0x5a, 0xb4, 0xf1, 0x37, 0x82, 0x38, 0x64,
	0x90, 0x21, 0xf4, 0x3f, 0x75, 0x69, 0x37, 0x5c, 0x89, 0x1a, 0x75, 0xd0, 0xe4, 0x1a, 0x62, 0x69,
	0x78, 0x9e, 0x6f, 0x3d, 0x30, 0x61, 0xb5, 0x22, 0x57, 0xd0, 0x55, 0x3a, 0x17, 0x05, 0xc5, 0xbe,
	0x1d, 0x84, 0x23, 0x95, 0xd2, 0x8a, 0xa5, 0xce, 0x05, 0xed, 0x04, 0x52, 0xa3, 0x9d, 0x57, 0xff,
	0x95, 0x8a, 0x76, 0x83, 0xd7, 0x68, 0x42, 0xa0, 0x63, 0xf9, 0xba, 0xa4, 0x71, 0x8a, 0xb3, 0x84,
	0xf9, 0x7a, 0xfc, 0x01, 0xfd, 0xe6, 0xbd, 0x4f, 0x76, 0xd1, 0xd9, 0xae, 0xf3, 0xb8, 0x95, 0x76,
	0x97, 0x87, 0x8f, 0x8e, 0xd8, 0x41, 0xbb, 0x73, 0x2d, 0xf4, 0x66, 0x1d, 0x4c, 0xec, 0xcd, 0x63,
	0xe3, 0xa9, 0xff, 0x16, 0xaf, 0x94, 0x79, 0x37, 0x8b, 0x45, 0xec, 0x2f, 0xd3, 0xec, 0x37, 0x00,
	0x00, 0xff, 0xff, 0xc2, 0x6e, 0xc2, 0x83, 0x59, 0x02, 0x00, 0x00,
}
