// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fmp.proto

package fmp_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//A structure containing all the devices listed in the network repo.
type Devices struct {
	Devices              map[string]*Device `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Timestamp            int64              `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Devices) Reset()         { *m = Devices{} }
func (m *Devices) String() string { return proto.CompactTextString(m) }
func (*Devices) ProtoMessage()    {}
func (*Devices) Descriptor() ([]byte, []int) {
	return fileDescriptor_936908a87da5a9ce, []int{0}
}

func (m *Devices) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Devices.Unmarshal(m, b)
}
func (m *Devices) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Devices.Marshal(b, m, deterministic)
}
func (m *Devices) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Devices.Merge(m, src)
}
func (m *Devices) XXX_Size() int {
	return xxx_messageInfo_Devices.Size(m)
}
func (m *Devices) XXX_DiscardUnknown() {
	xxx_messageInfo_Devices.DiscardUnknown(m)
}

var xxx_messageInfo_Devices proto.InternalMessageInfo

func (m *Devices) GetDevices() map[string]*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

func (m *Devices) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Device struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ipaddr               string   `protobuf:"bytes,2,opt,name=ipaddr,proto3" json:"ipaddr,omitempty"`
	Model                string   `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Sitecode             string   `protobuf:"bytes,4,opt,name=sitecode,proto3" json:"sitecode,omitempty"`
	Locality             string   `protobuf:"bytes,5,opt,name=locality,proto3" json:"locality,omitempty"`
	Tags                 []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_936908a87da5a9ce, []int{1}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Device) GetIpaddr() string {
	if m != nil {
		return m.Ipaddr
	}
	return ""
}

func (m *Device) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Device) GetSitecode() string {
	if m != nil {
		return m.Sitecode
	}
	return ""
}

func (m *Device) GetLocality() string {
	if m != nil {
		return m.Locality
	}
	return ""
}

func (m *Device) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*Devices)(nil), "fmp.Devices")
	proto.RegisterMapType((map[string]*Device)(nil), "fmp.Devices.DevicesEntry")
	proto.RegisterType((*Device)(nil), "fmp.Device")
}

func init() { proto.RegisterFile("fmp.proto", fileDescriptor_936908a87da5a9ce) }

var fileDescriptor_936908a87da5a9ce = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0xe5, 0xba, 0x4d, 0x9b, 0x0b, 0x03, 0x3a, 0x21, 0x64, 0x2a, 0x86, 0xd0, 0x29, 0x53,
	0x87, 0x76, 0x41, 0x8c, 0x08, 0xc4, 0xee, 0x91, 0x05, 0xb9, 0xb1, 0x03, 0x16, 0x71, 0x6d, 0xc5,
	0xa6, 0x52, 0xfe, 0x0c, 0x1b, 0xff, 0x13, 0xc5, 0x4e, 0xa0, 0x93, 0xdf, 0xf7, 0xde, 0xdd, 0xb3,
	0x74, 0x90, 0x37, 0xc6, 0x6d, 0x5d, 0x67, 0x83, 0x45, 0xda, 0x18, 0xb7, 0xf9, 0x21, 0xb0, 0x7c,
	0x52, 0x27, 0x5d, 0x2b, 0x8f, 0x7b, 0x58, 0xca, 0x24, 0x19, 0x29, 0x69, 0x55, 0xec, 0x6e, 0xb6,
	0xc3, 0xf4, 0x18, 0x4f, 0xef, 0xf3, 0x31, 0x74, 0x3d, 0x9f, 0x26, 0xf1, 0x16, 0xf2, 0xa0, 0x8d,
	0xf2, 0x41, 0x18, 0xc7, 0x66, 0x25, 0xa9, 0x28, 0xff, 0x37, 0xd6, 0x2f, 0x70, 0x71, 0xbe, 0x86,
	0x97, 0x40, 0x3f, 0x55, 0xcf, 0x48, 0x49, 0xaa, 0x9c, 0x0f, 0x12, 0xef, 0x60, 0x71, 0x12, 0xed,
	0x97, 0x8a, 0xbb, 0xc5, 0xae, 0x38, 0xfb, 0x92, 0xa7, 0xe4, 0x61, 0x76, 0x4f, 0x36, 0xdf, 0x04,
	0xb2, 0xe4, 0xe2, 0x1a, 0x56, 0x1f, 0xd6, 0x87, 0xa3, 0x30, 0x6a, 0x2c, 0xfa, 0x63, 0xbc, 0x86,
	0x4c, 0x3b, 0x21, 0x65, 0x17, 0xeb, 0x72, 0x3e, 0x12, 0x5e, 0xc1, 0xc2, 0x58, 0xa9, 0x5a, 0x46,
	0xa3, 0x9d, 0x60, 0x68, 0xf2, 0x3a, 0xa8, 0xda, 0x4a, 0xc5, 0xe6, 0xa9, 0x69, 0xe2, 0x21, 0x6b,
	0x6d, 0x2d, 0x5a, 0x1d, 0x7a, 0xb6, 0x48, 0xd9, 0xc4, 0x88, 0x30, 0x0f, 0xe2, 0xdd, 0xb3, 0xac,
	0xa4, 0x55, 0xce, 0xa3, 0x7e, 0x5c, 0xbd, 0x66, 0x8d, 0x71, 0x6f, 0xee, 0x70, 0xc8, 0xe2, 0x79,
	0xf7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x12, 0x2d, 0xc8, 0x6b, 0x01, 0x00, 0x00,
}
